
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "vagrant" do |vagrant2|
    vagrant2.vm.box = "ubuntu/trusty64"
    vagrant2.vm.network "forwarded_port", guest: 80, host: 8889
    vagrant2.vm.network "forwarded_port", guest: 443, host: 8443
  end
end
