- name: Provision a vagrant machine
  hosts: localhost
  vars:
    box: trusty64
  tasks:
    - name: create a Vagrantfile
      command: ./vagrant init {{ box }} creates=Vagrantfile
    - name: Bring up a vagrant machine
      command: ./vagrant up
    - name: add the vagrant machine to the inventory
      add_host: >
        name=vagrant
        ansible_host=127.0.0.1
        ansible_port=2222
        ansible_user=vagrant
        ansible_private_key_file=/Users/lorin/.vagrant.d/
        insecure_private_key