- name: show return value of command module
  hosts: vagrant4
  gather_facts: True
  tasks:
    - debug: var=ansible_distribution
    
    - name: capture output of id command
      command: id -un
      register: login
    - debug: msg="Logged in as user {{ login.stdout }}"

    - name: Run myprog
      command: /opt/myprog
      register: result
      ignore_errors: True
    - debug: var=result
